/**
 * Generates static bbox map for every icon in iconPaths.ts.
 *
 * Why this exists: Icon.tsx used to call getBBox() at runtime in useLayoutEffect,
 * causing a brief misalignment on first paint. Since each icon's bbox is a constant
 * derived from its path d (and any auxiliary <ellipse>), we precompute once.
 *
 * Run: npm run generate:icons
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import svgPathBoundsImport from 'svg-path-bounds';
import { ICON_PATHS, type IconName } from '../src/shared/ui/icons/Icon/iconPaths';

// svg-path-bounds is CJS; the default export is the function.
const svgPathBounds = (svgPathBoundsImport as unknown as (d: string) => [number, number, number, number]);

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../src/shared/ui/icons/Icon/iconBboxes.ts');

interface Bbox {
  x: number;
  y: number;
  width: number;
  height: number;
}

function extend(acc: { minX: number; minY: number; maxX: number; maxY: number }, x1: number, y1: number, x2: number, y2: number) {
  if (x1 < acc.minX) acc.minX = x1;
  if (y1 < acc.minY) acc.minY = y1;
  if (x2 > acc.maxX) acc.maxX = x2;
  if (y2 > acc.maxY) acc.maxY = y2;
}

function computeBbox(html: string): Bbox {
  const acc = { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity };

  // All <path d="...">
  const pathMatches = html.matchAll(/\bd="([^"]+)"/g);
  for (const m of pathMatches) {
    const [x1, y1, x2, y2] = svgPathBounds(m[1]);
    extend(acc, x1, y1, x2, y2);
  }

  // <ellipse cx="..." cy="..." rx="..." ry="...">
  const ellipseMatches = html.matchAll(/<ellipse\b[^>]*>/g);
  for (const tag of ellipseMatches) {
    const cx = Number(/cx="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    const cy = Number(/cy="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    const rx = Number(/rx="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    const ry = Number(/ry="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    extend(acc, cx - rx, cy - ry, cx + rx, cy + ry);
  }

  // <circle cx="..." cy="..." r="...">
  const circleMatches = html.matchAll(/<circle\b[^>]*>/g);
  for (const tag of circleMatches) {
    const cx = Number(/cx="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    const cy = Number(/cy="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    const r = Number(/\br="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    extend(acc, cx - r, cy - r, cx + r, cy + r);
  }

  // <rect x y width height>
  const rectMatches = html.matchAll(/<rect\b[^>]*>/g);
  for (const tag of rectMatches) {
    const x = Number(/\bx="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    const y = Number(/\by="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    const w = Number(/\bwidth="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    const h = Number(/\bheight="([^"]+)"/.exec(tag[0])?.[1] ?? '0');
    extend(acc, x, y, x + w, y + h);
  }

  if (!Number.isFinite(acc.minX)) {
    throw new Error('No drawable elements found');
  }

  return {
    x: acc.minX,
    y: acc.minY,
    width: acc.maxX - acc.minX,
    height: acc.maxY - acc.minY,
  };
}

function round(n: number): number {
  // 4 decimals — plenty of precision for SVG coords without bloating output.
  return Math.round(n * 10000) / 10000;
}

const names = Object.keys(ICON_PATHS) as IconName[];
const records: Array<[IconName, Bbox]> = [];

for (const name of names) {
  try {
    const bbox = computeBbox(ICON_PATHS[name]);
    records.push([
      name,
      {
        x: round(bbox.x),
        y: round(bbox.y),
        width: round(bbox.width),
        height: round(bbox.height),
      },
    ]);
  } catch (err) {
    console.error(`Failed to compute bbox for "${name}":`, err);
    process.exit(1);
  }
}

const body = records
  .map(([name, b]) => `  ${name}: { x: ${b.x}, y: ${b.y}, width: ${b.width}, height: ${b.height} },`)
  .join('\n');

const output = `// AUTO-GENERATED by scripts/generate-icon-bboxes.ts — do not edit by hand.
// Run \`npm run generate:icons\` to regenerate when iconPaths.ts changes.

import type { IconName } from './iconPaths';

export interface IconBbox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export const ICON_BBOXES: Record<IconName, IconBbox> = {
${body}
};
`;

writeFileSync(OUTPUT_PATH, output);
console.log(`Wrote ${records.length} bboxes to ${OUTPUT_PATH}`);
