// AUTO-GENERATED by scripts/generate-icon-bboxes.ts — do not edit by hand.
// Run `npm run generate:icons` to regenerate when iconPaths.ts changes.

import type { IconName } from './iconPaths';

export interface IconBbox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export const ICON_BBOXES: Record<IconName, IconBbox> = {
  burger: { x: 0, y: 0, width: 16, height: 12 },
  catalog: { x: 0, y: 0, width: 17.4941, height: 15.4941 },
  search: { x: 0, y: 0, width: 16, height: 16 },
  cross: { x: 4, y: 4, width: 12, height: 12 },
  repeat: { x: 3, y: 2, width: 14, height: 16 },
  minus: { x: 0, y: 0, width: 12, height: 1.3847 },
  plus: { x: 0, y: 0, width: 12, height: 12 },
  arrow: { x: 0, y: 0, width: 16, height: 16 },
  dropdown: { x: 0, y: 0, width: 16, height: 10 },
  dropup: { x: 0, y: 0, width: 16, height: 10 },
  arrow_left: { x: 0, y: 0, width: 10, height: 16 },
  arrow_right: { x: 0, y: 0, width: 10, height: 16 },
  drag: { x: 0, y: 0, width: 16.2382, height: 16.2382 },
  checkbox_empty: { x: 0, y: 0, width: 16, height: 16 },
  checkbox: { x: 0, y: 0, width: 16, height: 16 },
  check: { x: 0, y: 0, width: 16, height: 12 },
  like: { x: 0, y: 0, width: 16, height: 14 },
  like_filled: { x: 0, y: 0, width: 16, height: 14 },
  account: { x: 0, y: 0, width: 16, height: 16 },
  percent: { x: 0, y: 0, width: 16, height: 16 },
  address: { x: 0, y: 0, width: 14, height: 17 },
  cart: { x: 0, y: 0, width: 14, height: 16 },
  card: { x: 0, y: 0, width: 16, height: 17 },
  exit: { x: 0, y: 0, width: 16, height: 16 },
  sort: { x: 0, y: 0, width: 16, height: 15 },
  filter: { x: 0, y: 0, width: 16, height: 15 },
  delete: { x: 0, y: 0, width: 15.9756, height: 17 },
  edit: { x: 0, y: 0, width: 16, height: 16 },
  star: { x: -0.0165, y: 0, width: 16.033, height: 15.0124 },
  info: { x: 0, y: 0, width: 16, height: 16 },
  attention: { x: 0, y: 0, width: 16, height: 16 },
  question: { x: 0, y: 0, width: 16, height: 16 },
  wa: { x: 0, y: 0, width: 16.0009, height: 16 },
  vk: { x: 0, y: 0, width: 16, height: 16 },
  phone: { x: 0, y: 0, width: 16, height: 16 },
  tg: { x: 0, y: 0, width: 16, height: 16 },
  location: { x: 0, y: 0, width: 13, height: 16 },
  location_pin: { x: 0, y: 0, width: 14, height: 19 },
  ruble: { x: 0, y: 0, width: 9.3333, height: 11.6667 },
  payment: { x: 0, y: 0, width: 16, height: 12 },
  money: { x: 0, y: 0, width: 15, height: 15 },
  calendar: { x: 0, y: 0, width: 16, height: 16 },
  confirm: { x: 0, y: 0, width: 16, height: 15 },
  comment: { x: 0, y: 0, width: 16, height: 16 },
  setting: { x: 0, y: 0, width: 16, height: 16 },
  dot: { x: 0, y: 0, width: 16, height: 16 },
};
